# Generated by Django 3.2.8 on 2021-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('i', models.AutoField(db_column='I', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=60, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=100, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('i', models.AutoField(db_column='I', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
                ('time', models.TimeField(blank=True, db_column='TIME', null=True)),
                ('text', models.CharField(blank=True, db_column='TEXT', max_length=500, null=True)),
            ],
            options={
                'db_table': 'twitter',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='First',
        ),
    ]
